import openai
from openai import OpenAI
client =   OpenAI()
from main import text_content
def title_maker(text_content):
    print(text_content)
    os.environ["OPENAI_API_KEY"] = "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"
    class ChatCompletionMessage:
        def __init__(self, content, role, function_call=None, tool_calls=None):
            self.content = content
            self.role = role
            self.function_call = function_call
            self.tool_calls = tool_calls

        def get_text_content(self):
            # Return only the text content
            return self.content
        # Initialize the OpenAI client
    client = openai.OpenAI()

    # Your code for interacting with the OpenAI API goes here
# Your code for interacting with the OpenAI API goes here
    completion = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "you'll create powerful video titles for affirmation meditations on specific subjects by analyzing the affirmations and coming up with a noun or short phrase that sums up the new empowerment the individual is going to feel after listening to the affirmations. keep in mind these are going to be used to represent a video in an image so please only make it between three and five words long. it should feel very powerful and not cringe at all."},
            {"role": "user", "content": str(text_content)}
        ]
    )



    # Extract the actual content generated by GPT-3.5 Turbo
    generated_message = completion.choices[0].message
    generated_message_object = ChatCompletionMessage(
        content=generated_message.content,
        role='assistant'  # Assuming the role is 'assistant'
    )

    # Print out the text that will be read
    title = generated_message_object.get_text_content()
    return title
# next, use AI to generate title from affirmations